# Generated by Django 6.0.5 on 2026-06-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
