# Generated by Django 6.0.5 on 2026-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_main_image_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/main/'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to='products/variants/gallery/'),
        ),
    ]
