# Generated by Django 6.0.5 on 2026-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
