# Generated by Django 6.0.5 on 2026-07-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
