# Generated by Django 6.0.5 on 2026-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('razorpay', 'Razorpay'), ('refund', 'Refund'), ('referral', 'Referral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund'), ('cashback', 'Cashback'), ('referral', 'Referral Bonus')], max_length=20),
        ),
    ]
